[package]
name = "epic_asset_manager"
version = "2.2.2"
authors = ["Milan Stastny <milan@stastnej.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adw = { package = "libadwaita", version = "0.1.0-alpha-5" }
json5 = "0.4.1"
gettext-rs = { version = "0.7", features = ["gettext-system"] }
threadpool = "1.8"
secret-service = "2.0"
clap = "2.33"
env_logger = "0.9"
reqwest = { version = "0.11", features = ["json", "cookies", "blocking"] }
hex = "0.4"
lazy_static = "1.4"
once_cell = "1.8"
sha-1 = "0.9"
html2pango = "0.4.1"
byte-unit = "4.0"
slab_tree = "0.3"
log = "0.4"
gtk-macros = "0.3"
chrono = "0.4"
egs-api = "0.3.5"
git2 = "0.13.22"
version-compare = "0.0.13"

[dependencies.gtk4]
features = ["v4_2"]
version = "0.3"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.tokio]
version = "1"
features = ["full"]