[package]
name = "epic_asset_manager"
version = "1.0.10"
authors = ["Milan Stastny <milan@stastnej.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adw = { package = "libadwaita", version= "0.1.0-alpha-2" }
serde_json = "1.0"
gettext-rs = { version = "0.7", features = ["gettext-system"] }
relm-derive = "^0.22"
threadpool = "1.8.1"
dirs = "3.0"
config = "0.11"
secret-service = "2.0"
clap = "2.33.3"
env_logger = "0.9"
reqwest = { version = "0.11", features = ["json", "cookies", "blocking"] }
hex = "0.4"
lazy_static = "1.4"
once_cell = "1.8"
sha-1 = "0.9"
html2pango = "0.4.1"
byte-unit = "4.0"
slab_tree = "0.3"
log = "0.4"
gtk-macros = "0.3"
chrono = "0.4"
egs-api = "0.3.3"

[dependencies.gtk]
package = "gtk4"
features = ["v4_2"]
version = "0.2"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.tokio]
version = "1"
features = ["full"]