[package]
name = "epic_asset_manager"
version = "0.1.0"
authors = ["Milan Stastny <milan@stastnej.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = { version = "^0.9.0", features = ["v3_18"] }
webkit2gtk = "0.11.0"
gdk-pixbuf = "0.9.0"
glib = "0.10.3"
gio = { version = "0.9.1", features = ["v2_46"] }
serde_json = "1.0.62"
pango = "0.9.1"
relm = "^0.21.0"
relm-derive = "^0.21.0"
threadpool = "1.8.1"
dirs = "3.0.1"
config = "0.10.1"
clap = "2.33.3"
log = "0.4.14"
env_logger = "0.8.3"
reqwest = { version = "0.11", features = ["json", "cookies", "blocking"] }
hex = "0.4"
lazy_static = "1.4.0"

[dependencies.serde]
version = "1.0.123"
features = ["derive"]

[dependencies.egs-api]
git = "https://github.com/AchetaGames/egs-api-rs"

[dependencies.tokio]
version = "1.2.0"
features = ["full"]