[package]
name = "epic_asset_manager"
version = "3.5.2"
authors = ["Milan Stastny <milan@stastnej.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adw = { package = "libadwaita", version = "0.1.0" }
anyhow = "1.0"
byte-unit = "4.0"
chrono = "0.4"
clap = "3"
diesel = { version = "1.4", features = ["sqlite", "r2d2"] }
diesel_migrations = { version = "1.4", features = ["sqlite"] }
egs-api = "0.4"
env_logger = "0.9"
fs2 = "0.4.3"
futures = "0.3"
gtk4 = { version = "0.4", features = ["v4_6"] }
gtk-macros = "0.3"
hex = "0.4"
html2pango = "0.4"
lazy_static = "1.4"
libsqlite3-sys = { version = "0.22.2", features = ["bundled"] }
log = "0.4"
once_cell = "1.8"
rand = "0.8"
regex = "1"
reqwest = { version = "0.11", features = ["json", "cookies", "blocking"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha-1 = "0.10"
slab_tree = "0.3"
threadpool = "1.8"
tokio = "1"
version-compare = "0.1"

[target.'cfg(target_os = "windows")'.build-dependencies]
winres = "0.1"

[target.'cfg(target_os = "windows")'.dependencies]
open = "3"

[target.'cfg(target_os = "linux")'.dependencies]
ashpd = "0.3"
enumflags2 = "0.7.3"
gettext-rs = { version = "0.7", features = ["gettext-system"] }
ghregistry = "^0.2"
git2 = "0.14"
secret-service = "2.0"
