name: Rust

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prepare
      run: |
        sudo apt-get install -y libgtk-3-dev libsoup2.4-dev libwebkit2gtk-4.0-dev
        cargo update
    - name: Build
      run: cargo build --verbose

  linux-appimage-gui:
    strategy:
      matrix:
        toolchain: [ stable ]
        type: [ release ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true

      - uses: actions/cache@v2
        with:
          path: |
            target
          key: linux-appimage-gui-${{github.ref}}-${{github.sha}}
          restore-keys: |
            linux-appimage-gui-${{github.ref}}-${{github.sha}}
      - name: Install Gtk,
        run: sudo apt-get update; sudo apt install libgtk-3-dev libsoup2.4-dev libwebkit2gtk-4.0-dev librsvg2-dev libcairo2-dev wget -y

      - name: Build GUI Release
        run: cargo build --release
        env:
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: "-C debuginfo=0 -D warnings"

      - name: Download appimage dependiences
        run: |
          wget -c "https://raw.githubusercontent.com/linuxdeploy/linuxdeploy-plugin-gtk/master/linuxdeploy-plugin-gtk.sh"
          wget -c "https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage"
          chmod +x linuxdeploy-plugin-gtk.sh
          chmod +x linuxdeploy-x86_64.AppImage
          mkdir -p AppDir/usr/bin
          cp target/release/epic_asset_manager AppDir/usr/bin
          ./linuxdeploy-x86_64.AppImage --appdir AppDir --plugin gtk --output appimage --icon-file data/icons/input-gaming.png --desktop-file pkgs/com.github.achetagames.eam.desktop
      - name: Store Linux Appimage GUI
        uses: actions/upload-artifact@v2
        with:
          name: epic_asset_manager-appimage-${{ runner.os }}-${{ matrix.toolchain }}
          path: Epic*.AppImage