name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prepare
      run: |
        rustup install stable-x86_64-unknown-linux-gnu
        rustup update
        cargo clean
        cargo update
    - name: Build
      run: cargo build --verbose
